webimage_extra_packages:
    [
        chromium,
        gconf-service,
        libasound2,
        libatk1.0-0,
        libcairo2,
        libgconf-2-4,
        libgdk-pixbuf2.0-0,
        libgtk-3-0,
        libnspr4,
        libpango-1.0-0,
        libpangocairo-1.0-0,
        libx11-xcb1,
        libxcomposite1,
        libxcursor1,
        libxdamage1,
        libxfixes3,
        libxi6,
        libxrandr2,
        libxrender1,
        libxss1,
        libxtst6,
        fonts-liberation,
        libappindicator1,
        libnss3,
        xdg-utils,
    ]
web_environment:
    - CPPFLAGS=-DPNG_ARM_NEON_OPT=0
    - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
